name: Update warncells.md

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1,15 * *'

jobs:
  update_warncells:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: "actions/checkout@v4"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Execute Python Script
        run: python update_warncell_list.py
        working-directory: ./docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update warncells.md
          title: Update warncells.md
          body: Update warncells.md to reflect changes by DWD
          branch: update-warncellsmd
          delete-branch: true